# Generated by Django 5.2 on 2025-04-29 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_customuser_role_alter_tenant_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlord",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landlord_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
