# Generated by Django 4.2 on 2025-04-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_booking_id_alter_customuser_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="name",
            new_name="dorm_name",
        ),
        migrations.AddField(
            model_name="room",
            name="room_name",
            field=models.CharField(default="Room A", max_length=255),
            preserve_default=False,
        ),
    ]
