# Generated by Django 5.2 on 2025-04-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_rename_name_room_dorm_name_room_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
