# Generated by Django 5.2 on 2025-05-03 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_booking_room_alter_booking_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
