# Generated by Django 5.2 on 2025-05-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_delete_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="myapp.landlord",
            ),
        ),
    ]
