# Generated by Django 5.2 on 2025-05-04 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_roomimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="image",
        ),
    ]
