# Generated by Django 5.2 on 2025-05-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_remove_room_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="room_images/"),
        ),
        migrations.DeleteModel(
            name="RoomImage",
        ),
    ]
