# Generated by Django 5.2 on 2025-05-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_furniture_remove_room_furniture_room_furniture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="furniture",
        ),
        migrations.AddField(
            model_name="room",
            name="aircon_count",
            field=models.PositiveIntegerField(default=0, verbose_name="จำนวนแอร์"),
        ),
        migrations.AddField(
            model_name="room",
            name="bed_count",
            field=models.PositiveIntegerField(default=0, verbose_name="จำนวนเตียง"),
        ),
        migrations.AddField(
            model_name="room",
            name="chair_count",
            field=models.PositiveIntegerField(default=0, verbose_name="จำนวนเก้าอี้"),
        ),
        migrations.AddField(
            model_name="room",
            name="table_count",
            field=models.PositiveIntegerField(default=0, verbose_name="จำนวนโต๊ะ"),
        ),
        migrations.DeleteModel(
            name="Furniture",
        ),
    ]
