# Generated by Django 5.2 on 2025-05-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_remove_room_furniture_room_aircon_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="aircon_count",
            field=models.PositiveIntegerField(default=0, verbose_name="aircon_count"),
        ),
        migrations.AlterField(
            model_name="room",
            name="bed_count",
            field=models.PositiveIntegerField(default=0, verbose_name="bed_count"),
        ),
        migrations.AlterField(
            model_name="room",
            name="chair_count",
            field=models.PositiveIntegerField(default=0, verbose_name="chair_count"),
        ),
        migrations.AlterField(
            model_name="room",
            name="table_count",
            field=models.PositiveIntegerField(default=0, verbose_name="table_count"),
        ),
    ]
