# Generated by Django 5.2 on 2025-05-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_alter_room_aircon_count_alter_room_bed_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("tenant", "Tenant"), ("landlord", "Landlord")],
                max_length=20,
                null=True,
            ),
        ),
    ]
