# Generated by Django 5.2 on 2025-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="desk_count",
            field=models.PositiveIntegerField(default=0, verbose_name="desk_count"),
        ),
        migrations.AddField(
            model_name="room",
            name="refrigerator_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="refrigerator_count"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="sofa_count",
            field=models.PositiveIntegerField(default=0, verbose_name="sofa_count"),
        ),
        migrations.AddField(
            model_name="room",
            name="tv_count",
            field=models.PositiveIntegerField(default=0, verbose_name="tv_count"),
        ),
        migrations.AddField(
            model_name="room",
            name="wardrobe_count",
            field=models.PositiveIntegerField(default=0, verbose_name="wardrobe_count"),
        ),
        migrations.AddField(
            model_name="room",
            name="water_heater_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="water_heater_count"
            ),
        ),
    ]
