# Generated by Django 5.2 on 2025-05-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_room_desk_count_room_refrigerator_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="lease_duration_months",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Lease Duration (Months)"
            ),
        ),
    ]
