# Generated by Django 5.2 on 2025-05-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_room_lease_duration_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlord",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="landlord",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="landlord",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="landlord",
            name="dorm_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
