# Generated by Django 5.2 on 2025-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_landlord_account_holder_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlord",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
